### ISSUE TITLE
Selenium runs regularly fail in production

### ISSUE THREAD

**Issue by manuelkiessling** [journeymonitor/monitor#4]
Looks like Selenese runner is not able to start Firefox:

```
{"port":29618}[2016-01-13 08:10:17.462] [INFO] Start: Selenese Runner 1.10.0
[2016-01-13 08:10:17.773] [INFO] Command line arguments: [--new-instance] [--profile /var/tmp/journeymonitor-firefox-profile-14667]
org.openqa.selenium.WebDriverException: Unable to bind to locking port 7054 within 45000 ms
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'v22015051223725490', ip: '37.120.178.155', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-68-generic', java.version: '1.7.0_79'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.internal.SocketLock.lock(SocketLock.java:98)
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:84)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:246)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:114)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:103)
	at jp.vmi.selenium.webdriver.FirefoxDriverFactory.newInstance(FirefoxDriverFactory.java:139)
	at jp.vmi.selenium.webdriver.WebDriverManager$Builder.build(WebDriverManager.java:86)
	at jp.vmi.selenium.webdriver.WebDriverManager.get(WebDriverManager.java:315)
	at jp.vmi.selenium.selenese.Main.setupRunner(Main.java:138)
	at jp.vmi.selenium.selenese.Main.run(Main.java:87)
	at jp.vmi.selenium.selenese.Main.main(Main.java:218)
[2016-01-13 08:11:04.534] [INFO] Exit code: 1
```

**Comment by manuelkiessling** [comment]
Firefox on production systems is at 43.0.3 from December 2015, looks like it's regularly updated (due to unattended security updates?). Thus, journeymonitor/infra/issues/7 might fix this.

**Comment by manuelkiessling** [comment]
Yep, according to `zcat /var/log/apt/history.log.*.gz | grep -i firefox`, Firefox got updated from 38 to 43 over time.

**Comment by manuelkiessling** [comment]
Todo: Check if start of the run failures correlates with a certain Firefox upgrade.

**Comment by manuelkiessling** [comment]
Assumed fixed.
